apiVersion: v1
kind: PersistentVolume
metadata:
  name: pji-grupo1-codigo
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ensino/pji_grupo1/codigo
