kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pji-grupo1-codigo
  namespace: ensino
  labels:
    namespace: ensino
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
