kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pji-grupo1-codigo
  labels:
    app: pji-grupo1-codigo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
