kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pji-grupo1-mariadb
  labels:
    app: pji-grupo1-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
