apiVersion: v1
kind: PersistentVolume
metadata:
  name: pji-grupo1-mariadb
  labels:
    namespace: ensino
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ensino/pji_grupo1/mariadb
